<a href="https://colab.research.google.com/github/JohnParken/Machine-Learning-in-Action/blob/master/02_%E9%A2%84%E5%A4%87%E7%9F%A5%E8%AF%86.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
!sudo lsb_release -a

No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.2 LTS
Release:	18.04
Codename:	bionic


In [0]:
!pip install mxnet-cu100

### 2.2数据操作

#### 2.1 创建NDArray

In [0]:
from mxnet import nd

In [0]:
x = nd.arange(12)
x


[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11.]
<NDArray 12 @cpu(0)>

In [0]:
x.shape

(12,)

In [0]:
x.size

12

In [0]:
X = x.reshape(-1,4)
X


[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]
<NDArray 3x4 @cpu(0)>

In [0]:
nd.zeros((2,3,4))


[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]
<NDArray 2x3x4 @cpu(0)>

In [0]:
nd.ones((3,4))


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
<NDArray 3x4 @cpu(0)>

In [0]:
Y = nd.array([[2,3,4,5],[0,1,2,3],[0,1,2,3]])
Y


[[2. 3. 4. 5.]
 [0. 1. 2. 3.]
 [0. 1. 2. 3.]]
<NDArray 3x4 @cpu(0)>

In [0]:
nd.random.normal(0,1,shape=(3,4))


[[-0.9712193  -0.58256227  0.3717077   0.9300072 ]
 [-1.4225755  -0.5176199   2.0088325   0.2863085 ]
 [ 0.5604595   0.96975976 -0.52853745 -1.88909   ]]
<NDArray 3x4 @cpu(0)>

#### 2.2.2 运算

In [0]:
X + Y


[[ 2.  4.  6.  8.]
 [ 4.  6.  8. 10.]
 [ 8. 10. 12. 14.]]
<NDArray 3x4 @cpu(0)>

In [0]:
X / Y


[[0.         0.33333334 0.5        0.6       ]
 [       inf 5.         3.         2.3333333 ]
 [       inf 9.         5.         3.6666667 ]]
<NDArray 3x4 @cpu(0)>

In [0]:
X * Y


[[ 0.  3.  8. 15.]
 [ 0.  5. 12. 21.]
 [ 0.  9. 20. 33.]]
<NDArray 3x4 @cpu(0)>

In [0]:
Y.exp()


[[  7.389056   20.085537   54.59815   148.41316  ]
 [  1.          2.7182817   7.389056   20.085537 ]
 [  1.          2.7182817   7.389056   20.085537 ]]
<NDArray 3x4 @cpu(0)>

In [0]:
nd.dot(X,Y.T)


[[ 26.  14.  14.]
 [ 82.  38.  38.]
 [138.  62.  62.]]
<NDArray 3x3 @cpu(0)>

In [0]:
nd.concat(X, Y, dim=0), nd.concat(X, Y, dim=1)

(
 [[ 0.  1.  2.  3.]
  [ 4.  5.  6.  7.]
  [ 8.  9. 10. 11.]
  [ 2.  3.  4.  5.]
  [ 0.  1.  2.  3.]
  [ 0.  1.  2.  3.]]
 <NDArray 6x4 @cpu(0)>, 
 [[ 0.  1.  2.  3.  2.  3.  4.  5.]
  [ 4.  5.  6.  7.  0.  1.  2.  3.]
  [ 8.  9. 10. 11.  0.  1.  2.  3.]]
 <NDArray 3x8 @cpu(0)>)

In [0]:
X == Y


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
<NDArray 3x4 @cpu(0)>

In [0]:
X.sum()


[66.]
<NDArray 1 @cpu(0)>

In [0]:
# x的L2范数标量
X.norm().asscalar() 

22.494442

#### 2.2.3 广播机制

In [0]:
A = nd.arange(3).reshape(3,-1)
B = nd.arange(2).reshape(-1,2)
A,B

(
 [[0.]
  [1.]
  [2.]]
 <NDArray 3x1 @cpu(0)>, 
 [[0. 1.]]
 <NDArray 1x2 @cpu(0)>)

In [0]:
A+B


[[0. 1.]
 [1. 2.]
 [2. 3.]]
<NDArray 3x2 @cpu(0)>

#### 2.2.4 索引

In [0]:
X[1:3]


[[ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]
<NDArray 2x4 @cpu(0)>

In [0]:
X[1,2] = 9
X


[[ 0.  1.  2.  3.]
 [ 4.  5.  9.  7.]
 [ 8.  9. 10. 11.]]
<NDArray 3x4 @cpu(0)>

In [0]:
X[1:2,:] = 12
X


[[ 0.  1.  2.  3.]
 [12. 12. 12. 12.]
 [ 8.  9. 10. 11.]]
<NDArray 3x4 @cpu(0)>

#### 2.2.5 运算的内存开销

In [0]:
# 运算的内存开销
before = id(Y)
Y = Y + X
id(Y) == before

False

In [0]:
Z = Y.zeros_like()
before = id(Z)
Z[:] = X + Y
id(Z) == before

True

#### 2.2.6 NDArray和NumPy相互转换

In [0]:
import numpy as np

In [0]:
P = np.ones((2,3))
D = nd.array(P)
D


[[1. 1. 1.]
 [1. 1. 1.]]
<NDArray 2x3 @cpu(0)>

In [0]:
D.asnumpy()

array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)

#### 练习1

In [0]:
X > Y


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
<NDArray 3x4 @cpu(0)>

In [0]:
X < Y


[[1. 1. 1. 1.]
 [0. 1. 1. 1.]
 [0. 1. 1. 1.]]
<NDArray 3x4 @cpu(0)>

#### 练习2
只有当其中一个矩阵是n*1的时候才能广播

In [0]:
C = nd.arange(6).reshape(6,-1)
C


[[0.]
 [1.]
 [2.]
 [3.]
 [4.]
 [5.]]
<NDArray 6x1 @cpu(0)>

In [0]:
D = nd.arange(4).reshape(1,4)
D


[[0. 1. 2. 3.]]
<NDArray 1x4 @cpu(0)>

In [0]:
C + D


[[0. 1. 2. 3.]
 [1. 2. 3. 4.]
 [2. 3. 4. 5.]
 [3. 4. 5. 6.]
 [4. 5. 6. 7.]
 [5. 6. 7. 8.]]
<NDArray 6x4 @cpu(0)>

### 2.3 自动求梯度

#### 2.3.1 简单例子

In [0]:
from mxnet import autograd, nd

In [0]:
x = nd.arange(4).reshape(4,1)
x


[[0.]
 [1.]
 [2.]
 [3.]]
<NDArray 4x1 @cpu(0)>

In [0]:
x.attach_grad()

In [0]:
with autograd.record():
  y = 2 * nd.dot(x.T,x)

In [0]:
y.backward()

In [0]:
assert (x.grad - 4*x).norm().asscalar() == 0
x.grad


[[ 0.]
 [ 4.]
 [ 8.]
 [12.]]
<NDArray 4x1 @cpu(0)>

#### 2.3.2 训练模式和预测模式

In [0]:
print(autograd.is_training())
with autograd.record():
  print(autograd.is_training())

False
True


In [0]:
def f(a):
  b = a * 2
  while b.norm().asscalar() < 1000:
    b = b *2
  if b.sum().asscalar() > 0:
    c = b
  else:
    c = 100 * b
  return c

In [0]:
a = nd.random.normal(shape=1)
a.attach_grad()
with autograd.record():
  c = f(a)
c.backward()

In [0]:
a.grad == c / a


[1.]
<NDArray 1 @cpu(0)>